default: &default
  type: bigquery
  method: service-account
  project: sbh-nycitibike-pipeline-main
  location: us-central1
  threads: 4
  timeout_seconds: 300
  priority: interactive
  retries: 1

nycitibike_transform:
  target: DEV
  outputs:
    DEV:
      <<: *default
      schema: "DEV"
      keyfile: "../../secrets/dbt-trnsfrm-sa2-key-clrn-secret-file.json"
      # dataset: GBQDWH_RIDES
    PROD:
      <<: *default
      schema: "CORE"
      keyfile:
          env_var: DBT_SA_CREDS
      # dataset: DEV_GBQDWH_RIDES
